// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOAqTrztaIL64-rbjbH4w1yBHOu76iAN4',
    appId: '1:541810139092:web:2a3693ad09130adee98041',
    messagingSenderId: '541810139092',
    projectId: 'dailyapp-52ddd',
    authDomain: 'dailyapp-52ddd.firebaseapp.com',
    storageBucket: 'dailyapp-52ddd.firebasestorage.app',
    measurementId: 'G-SZJW3GEX5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR6c4kBGxbu6FvujpK49FwOhwMA0Ce6us',
    appId: '1:541810139092:android:6a10c194bf4b7868e98041',
    messagingSenderId: '541810139092',
    projectId: 'dailyapp-52ddd',
    storageBucket: 'dailyapp-52ddd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs0Sl615YFTSsQGVS2iC2Znrv4jIiai8c',
    appId: '1:541810139092:ios:1dd30f13deb1ab1ee98041',
    messagingSenderId: '541810139092',
    projectId: 'dailyapp-52ddd',
    storageBucket: 'dailyapp-52ddd.firebasestorage.app',
    iosClientId: '541810139092-7k73034pn9v4qaovodebnbhrgbr7vpb3.apps.googleusercontent.com',
    iosBundleId: 'com.antigravity.dailyAgenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs0Sl615YFTSsQGVS2iC2Znrv4jIiai8c',
    appId: '1:541810139092:ios:1dd30f13deb1ab1ee98041',
    messagingSenderId: '541810139092',
    projectId: 'dailyapp-52ddd',
    storageBucket: 'dailyapp-52ddd.firebasestorage.app',
    iosClientId: '541810139092-7k73034pn9v4qaovodebnbhrgbr7vpb3.apps.googleusercontent.com',
    iosBundleId: 'com.antigravity.dailyAgenda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOAqTrztaIL64-rbjbH4w1yBHOu76iAN4',
    appId: '1:541810139092:web:e2956108299c5a1ae98041',
    messagingSenderId: '541810139092',
    projectId: 'dailyapp-52ddd',
    authDomain: 'dailyapp-52ddd.firebaseapp.com',
    storageBucket: 'dailyapp-52ddd.firebasestorage.app',
    measurementId: 'G-7ZGMJC5YKM',
  );
}
